<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
  $data = 'c6nb73q5tfpyy64f:3cc9e33a4a98464548614fd16337fe33';
  $data = base64_encode($data); // encoded to base 64
  //echo $data; //printed 

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://payments.sandbox.braintree-api.com/graphql');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"query\": \"query { ping }\"}");

$headers = array();
$headers[] = 'Authorization: Basic '. $data;
print_r($headers); //    [0] => Authorization: Basic YzZuYjczcTV0ZnB5eTY0ZjozY2M5ZTMzYTRhOTg0NjQ1NDg2MTRmZDE2MzM3ZmUzMw==
$headers[] = 'Braintree-Version: 2019-01-01';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

echo $result; //{"data":{"ping":"pong"},"extensions":{"requestId":"c15a0fb2-c1cb-4ce3-9249-93a0417003a5"}} //success

?>